### ISSUE TITLE
Image format not supported no matter the image I use

### ISSUE THREAD

**Issue by aliumujib** [Rogero0o/MissView#1]
Hi, I am trying to use the library as part of the starting screen for my app, but when I use any image apart from the "night.png" supplied with the library demo, I get the error, Image format not supported. 
This is the stack trace:

java.io.IOException: Image format not supported
05-01 18:08:21.559 23433-23476/com.alium.spacetraders W/System.err:     at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
05-01 18:08:21.559 23433-23476/com.alium.spacetraders W/System.err:     at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
05-01 18:08:21.559 23433-23476/com.alium.spacetraders W/System.err:     at com.roger.missview.library.util.BitmapRegionLoader.<init>(BitmapRegionLoader.java:69)
05-01 18:08:21.559 23433-23476/com.alium.spacetraders W/System.err:     at com.roger.missview.library.util.BitmapRegionLoader.newInstance(BitmapRegionLoader.java:53)
05-01 18:08:21.559 23433-23476/com.alium.spacetraders W/System.err:     at com.roger.missview.library.util.BitmapRegionLoader.newInstance(BitmapRegionLoader.java:44)
05-01 18:08:21.561 23433-23476/com.alium.spacetraders W/System.err:     at com.roger.missview.library.DemoRenderController.openDownloadedCurrentArtwork(DemoRenderController.java:99)
05-01 18:08:21.561 23433-23476/com.alium.spacetraders W/System.err:     at com.roger.missview.library.RenderController$1.doInBackground(RenderController.java:52)
05-01 18:08:21.561 23433-23476/com.alium.spacetraders W/System.err:     at com.roger.missview.library.RenderController$1.doInBackground(RenderController.java:48)
05-01 18:08:21.562 23433-23476/com.alium.spacetraders W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
05-01 18:08:21.562 23433-23476/com.alium.spacetraders W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-01 18:08:21.562 23433-23476/com.alium.spacetraders W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
05-01 18:08:21.562 23433-23476/com.alium.spacetraders W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-01 18:08:21.562 23433-23476/com.alium.spacetraders W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-01 18:08:21.562 23433-23476/com.alium.spacetraders W/System.err:     at java.lang.Thread.run(Thread.java:818)

Any help such as specifics on which image format or encoding or anything at all will be helpfull, thanks. You might also include such a detail in the readme.md file.

**Comment by thedumbtechguy** [comment]
Can I see the code you used?

**Comment by aliumujib** [comment]
I made a mistake of placing my assets folder in the recources folder. Thanks for the help earlier Roger.

Cheers.

**Comment by thedumbtechguy** [comment]
I suspected as much. Glad you fixed it.
