### ISSUE TITLE
Ugly black screen

### ISSUE THREAD

**Issue by RamiTrabelsi** [Rogero0o/MissView#3]
I thank you for this beautiful library, therefore when loading at start there is a black ugly screen. Can we overcome it ?

**Comment by Rogero0o** [comment]
Sorry , i don't get your point . And in my case , there is no black screen when loading , check weather your image is too big .

**Comment by RamiTrabelsi** [comment]
The Black screen happens just when the activity opens (onWindowFocusChanged). The size of my image is the same as put in the sample

**Comment by tochange** [comment]
没接触过openGL, 感觉发热过于严重，还没找到哪里可以修改，谢谢。

另，我也是在厦门念书的，现在在北京。

**Comment by tochange** [comment]
同样，刚起来的时候，我这边也是，黑屏的，得过了一两秒才好起来。

**Comment by Rogero0o** [comment]
I have check this problem and found out that it's cause by the progress of loading image to a 'GLPicture' array . It takes about 1.5s . 

## I can't solve it because it's a important method but i will try another way to improve it.

查了一下可能是在将图片加载为一个 'GLPicture' 数组的时候耗时比较长.暂时没有找到一个好办法来解决这个问题 ...

**Comment by tochange** [comment]
mBitmapRegionDecoder = BitmapRegionDecoder.newInstance();// first parameter no need to use inputstream, just pass file path..
